### ISSUE TITLE
GaxError Exception occurred in retry method that was not classified as transient, caused by 5:Requested entity was not found

### ISSUE THREAD

**Issue by Toshiuk** [googleads/google-ads-ruby#107]
When I tried to use keyword_plan_idea_service_client.rb to list keyword ideas, always return this error to me:

Error: 'GaxError Exception occurred in retry method that was not classified as transient, caused by 5:Requested entity was not found.'
	Cause: '5:Requested entity was not found.'
	Code: 5
	Details: 'Requested entity was not found.'
	Request-Id: 'MNH7cNiC8MpCzHokdPDu_Q'

Example:
```
kp_idea_service = client.service(:KeywordPlanIdea)
    
seed = client.resource(:UrlSeed)
seed.url = client.wrapper.string("github.com")

      kp_idea_service.generate_keyword_ideas(
        customer_id,
        client.wrapper.string(client.path.language_constant('en_US')),
        [client.wrapper.string(client.path.geo_target_constant(2076))],
        client.enum(:KeywordPlanNetwork)::GOOGLE_SEARCH,
        url_seed: seed
      )
  
```
```
/home/toshi/.rvm/gems/ruby-2.6.0/gems/google-gax-1.5.0/lib/google/gax/api_callable.rb:369:in `rescue in block in retryable'
/home/toshi/.rvm/gems/ruby-2.6.0/gems/google-gax-1.5.0/lib/google/gax/api_callable.rb:358:in `block in retryable'
/home/toshi/.rvm/gems/ruby-2.6.0/gems/google-gax-1.5.0/lib/google/gax/api_callable.rb:230:in `block in create_api_call'
/home/toshi/.rvm/gems/ruby-2.6.0/gems/google-gax-1.5.0/lib/google/gax/api_callable.rb:260:in `block in create_api_call'
/home/toshi/.rvm/gems/ruby-2.6.0/gems/google-ads-googleads-1.1.1/lib/google/ads/google_ads/v1/services/keyword_plan_idea_service_client.rb:245:in `generate_keyword_ideas'
teste.rb:55:in `generate_keyword_ideas'
teste.rb:145:in `<main>'
```

**Comment by mcloonan** [comment]
If you rescue the error, is it a Google::Ads::GoogleAds::Errors::GoogleAdsError or something else? Can you provide the results of error.inspect? Can you also turn on logging and provide the request/response logs?

**Comment by Toshiuk** [comment]
It resulted in a very generic error. I was using the wrong id_language type, it had to be a number.
