### ISSUE TITLE
Field search appears to be broken

### ISSUE THREAD

**Issue by samphippen** [googleads/google-ads-ruby#37]
```
[2] pry(main)> c
=> #<Google::Ads::GoogleAds::GoogleAdsClient:0x00007f920438fa20
... (redacted)
>
[3] pry(main)> fs = c.service(:GoogleAdsField)
=> #<#<Class:0x00007f9204435538>:0x00007f9204434c00
 @get_google_ads_field=#<Proc:0x00007f9204425070@/Users/samphippen/.gem/ruby/2.5.3/gems/google-gax-1.5.0/lib/google/gax/api_callable.rb:246>,
 @google_ads_field_service_stub=
  #<Google::Ads::GoogleAds::V0::Services::GoogleAdsFieldService::Stub:0x00007f9204425368
   @ch=#<GRPC::Core::Channel:0x00007f92044251b0>,
   @host="googleads.googleapis.com:443",
   @interceptors=
    #<GRPC::InterceptorRegistry:0x00007f9204425160
     @interceptors=
      [#<Google::Ads::GoogleAds::LoggingInterceptor:0x00007f92044354c0
        @logger=
         #<Logger:0x00007f920438f7a0
          @default_formatter=#<Logger::Formatter:0x00007f920438f700 @datetime_format=nil>,
          @formatter=nil,
          @level=1,
          @logdev=#<Logger::LogDevice:0x00007f920438f6b0 @dev=#<IO:<STDERR>>, @filename=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x00007f920438f5e8>, @mon_owner=nil, @shift_age=nil, @shift_period_suffix=nil, @shift_size=nil>,
          @progname=nil>,
        @options={}>]>,
   @propagate_mask=nil,
   @timeout=1969-12-31 18:59:59 -0500>,
 @search_google_ads_fields=#<Proc:0x00007f9204424f58@/Users/samphippen/.gem/ruby/2.5.3/gems/google-gax-1.5.0/lib/google/gax/api_callable.rb:246>>
[4] pry(main)> fs.search_google_ads_fields('')
Google::Gax::RetryError: GaxError Exception occurred in retry method that was not classified as transient, caused by undefined method `customer_id' for #<Google::Ads::GoogleAds::V0::Services::SearchGoogleAdsFieldsRequest:0x00007f92043787a8>
from /Users/samphippen/.gem/ruby/2.5.3/gems/google-gax-1.5.0/lib/google/gax/api_callable.rb:369:in `rescue in block in retryable'
Caused by NoMethodError: undefined method `customer_id' for #<Google::Ads::GoogleAds::V0::Services::SearchGoogleAdsFieldsRequest:0x00007f92043787a8>
from /Users/samphippen/.gem/ruby/2.5.3/gems/google-ads-googleads-0.8.0/lib/google/ads/google_ads/logging_interceptor.rb:34:in `method_missing'
[5] pry(main)> fs.search_google_ads_fields('select * from foo')
Google::Gax::RetryError: GaxError Exception occurred in retry method that was not classified as transient, caused by undefined method `customer_id' for #<Google::Ads::GoogleAds::V0::Services::SearchGoogleAdsFieldsRequest:0x00007f920436fdd8>
from /Users/samphippen/.gem/ruby/2.5.3/gems/google-gax-1.5.0/lib/google/gax/api_callable.rb:369:in `rescue in block in retryable'
Caused by NoMethodError: undefined method `customer_id' for #<Google::Ads::GoogleAds::V0::Services::SearchGoogleAdsFieldsRequest:0x00007f920436fdd8>
from /Users/samphippen/.gem/ruby/2.5.3/gems/google-ads-googleads-0.8.0/lib/google/ads/google_ads/logging_interceptor.rb:34:in `method_missing'
[6] pry(main)>
```

I would have expected this to correctly dispatch a request, not try and call customer_id on a proto that doesn't have it.

**Comment by mcloonan** [comment]
I think this is the same as issue #26 so the same PR should fix it once I can get that through.
