### ISSUE TITLE
Infine loop retrying with expired token

### ISSUE THREAD

**Issue by troex** [googleads/google-ads-ruby#389]
**Describe the bug:**
When query is executed with expired token it results in endless retry loop which is not catchable with `rescue`

**Steps to Reproduce:**
Execute query with exired refresh_token

**Expected behavior:**
Library should raise proper error instead of doing infinite retry

**Client library version and API version:**
Client library version: 16.0
Google Ads API version: v10

**Request/Response Logs:**

```
W, [2022-04-19T21:37:43.353323 #4]  WARN -- : CID: 1853062519, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v10.services.GoogleAdsService/Search, IsFault: yes, Request ID:
I, [2022-04-19T21:37:43.353520 #4]  INFO -- : Outgoing request: Headers: {"developer-token":"REDACTED","x-goog-api-client":"gl-ruby/3.0.2 gccl/16.0.0 gax/0.6.0 gapic/16.0.0 grpc/1.43.1","x-goog-request-params":"customer_id=1853062519"} Payload: {"customerId":"1853062519","query":"SELECT\n  campaign.id,\n  ad_group.id,\n  click_view.gclid,\n  click_view.keyword,\n  click_view.keyword_info.text\nFROM click_view\nWHERE\n  segments.date = '2022-04-19'\n","pageSize":1000}
I, [2022-04-19T21:37:43.353602 #4]  INFO -- : Incoming response (errors):
  GRPC::Unavailable(14:Getting metadata from plugin failed with error: #<Signet::AuthorizationError: Authorization failed.  Server message:
{
  "error": "invalid_grant",
  "error_description": "Token has been expired or revoked."
}>. debug_error_string:{"created":"@1650404263.352986162","description":"Getting metadata from plugin failed with error: #<Signet::AuthorizationError: Authorization failed.  Server message:\n{\n  "error": "invalid_grant",\n  "error_description": "Token has been expired or revoked."\n}>","file":"src/core/lib/security/credentials/plugin/plugin_credentials.cc","file_line":91,"grpc_status":14}):
  called from: /app/lib/services/googleads2/api.rb:306:in `execute_query'
W, [2022-04-19T21:37:48.394785 #4]  WARN -- : CID: 1853062519, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v10.services.GoogleAdsService/Search, IsFault: yes, Request ID:
I, [2022-04-19T21:37:48.394988 #4]  INFO -- : Outgoing request: Headers: {"developer-token":"REDACTED","x-goog-api-client":"gl-ruby/3.0.2 gccl/16.0.0 gax/0.6.0 gapic/16.0.0 grpc/1.43.1","x-goog-request-params":"customer_id=1853062519"} Payload: {"customerId":"1853062519","query":"SELECT\n  campaign.id,\n  ad_group.id,\n  click_view.gclid,\n  click_view.keyword,\n  click_view.keyword_info.text\nFROM click_view\nWHERE\n  segments.date = '2022-04-19'\n","pageSize":1000}
I, [2022-04-19T21:37:48.395062 #4]  INFO -- : Incoming response (errors):
  GRPC::Unavailable(14:Getting metadata from plugin failed with error: #<Signet::AuthorizationError: Authorization failed.  Server message:
{
  "error": "invalid_grant",
  "error_description": "Token has been expired or revoked."
}>. debug_error_string:{"created":"@1650404268.394336921","description":"Getting metadata from plugin failed with error: #<Signet::AuthorizationError: Authorization failed.  Server message:\n{\n  "error": "invalid_grant",\n  "error_description": "Token has been expired or revoked."\n}>","file":"src/core/lib/security/credentials/plugin/plugin_credentials.cc","file_line":91,"grpc_status":14}):
  called from: /app/lib/services/googleads2/api.rb:306:in `execute_query'
```

**Anything else we should know about your project / environment:**

**Comment by troex** [comment]
related issue https://github.com/googleads/google-ads-ruby/issues/246

**Comment by mcloonan** [comment]
This isn't just related; it's the same issue as #246. This is, unfortunately, a side effect of the auth layer in a dependency of ours. We're still working with them to try to get this resolved.

Unfortunately, I don't have an estimate of when that might happen.
